---
title: "Data wrangling for CGM, physical activity, sleep, diet"
date: "11/12/2022"
author: "Alireza Delfarah"
---

#libraries
```{r}
library(plyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape)
library(reshape2); 
library(grid)
library(gridExtra)
library(scales)
library(RColorBrewer)
library(extrafont)
library(ggpubr)
library(factoextra)
library(matrixStats)
library("writexl")
library(psycho)
library(lubridate)
library("rjson")
library(readtext)
library(readr)
library(stringr)
library(viridis)
library(hms)
library(anytime)
loadfonts()
```
#import data
```{r}
cgm = read_csv("cgm.csv")
cgm_cycles = read_csv("cycles.csv")
diet = read_csv("data2_cat_v3.csv")
activity_index_all = read_csv("activity_index_all.csv")
meta.lab.v2 = read_csv("meta_lab_1_v2.csv")
diet_timing = read_csv("diet_timing.csv")
sleep = read_csv("data_sleep_cycle123.csv")
steps_all = read_csv("steps_all.csv")
```
#data wrangling
```{r}
##############################################################################################
#data wrangling for CGM, physical activity, sleep, diet
#data for steps, energy, and carb scaled to 0 to 1 after summing values for each time-window
##############################################################################################

cgm$date_time <- as_datetime(cgm$time)
cgm$date <- as_date(cgm$date_time)
cgm$time_of_day <- format(as.POSIXct(cgm$date_time), format = "%H:%M:%S")
cgm$time_of_day_2 <- as_hms(cgm$date_time)
cgm$time_numeric <- as.numeric(cgm$time_of_day_2)

cgm['timing'] <- NA
cgm <- cgm %>% relocate(timing, .before = time)

cgm$timing[cgm$time_numeric > 0 & cgm$time_numeric < 18000] <- "cgm-midnight-5am"
cgm$timing[cgm$time_numeric > 18000 & cgm$time_numeric < 28800] <- "cgm-5am-8am"
cgm$timing[cgm$time_numeric > 28800 & cgm$time_numeric < 39600] <- "cgm-8am-11am"
cgm$timing[cgm$time_numeric > 39600 & cgm$time_numeric < 50400] <- "cgm-11am-2pm"
cgm$timing[cgm$time_numeric > 50400 & cgm$time_numeric < 61200] <- "cgm-2pm-5pm"
cgm$timing[cgm$time_numeric > 61200 & cgm$time_numeric < 75600] <- "cgm-5pm-9pm"
cgm$timing[cgm$time_numeric > 75600 & cgm$time_numeric < 86400] <- "cgm-9pm-midnight"
cgm$timing <- factor(cgm$timing , levels=c("cgm-midnight-5am","cgm-5am-8am","cgm-8am-11am","cgm-11am-2pm", "cgm-2pm-5pm", "cgm-5pm-9pm", "cgm-9pm-midnight"))

#calculate average cgm for each day and zones
#daily avg
daily.CGM <- aggregate(cgm$CGM, by=list(ID=cgm$ID, date = cgm$date), FUN=mean)
x <- c("ID", "date", "avg_CGM")
colnames(daily.CGM) <- x

#zones avg
daily.CGM.zones <- aggregate(cgm$CGM, by=list(ID=cgm$ID, date = cgm$date, timing = cgm$timing), FUN=mean)
x <- c("ID", "date", "timing", "avg_CGM")
colnames(daily.CGM.zones) <- x

#long to wide format for zones
daily.CGM.zones.wide <- dcast(daily.CGM.zones, ID + date ~ timing)
daily.CGM.zones.wide <- daily.CGM.zones.wide[complete.cases(daily.CGM.zones.wide), ]
daily.CGM.zones.wide = left_join(daily.CGM.zones.wide,daily.CGM,by=c("ID"="ID", "date"="date"))

#remove day gaps
daily.CGM.zones.wide$day_number_CGM_no_gap <- daily.CGM.zones.wide$day_number_CGM.x
daily.CGM.zones.wide.days <- daily.CGM.zones.wide[1,]
daily.CGM.zones.wide.days <- daily.CGM.zones.wide.days[-1,]

for (p in unique(daily.CGM.zones.wide$ID))
{
  i=1
  temp <- daily.CGM.zones.wide[(daily.CGM.zones.wide$ID == p),]
  for (n in unique(temp$day_number_CGM.x))
    {
    temp$day_number_CGM_no_gap[which(temp$day_number_CGM.x == n)] <- i
    i=i+1}
  daily.CGM.zones.wide.days <- rbind(daily.CGM.zones.wide.days,temp)
  }
    
steps_all$timing <- factor(steps_all$timing , levels=c("midnight-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-midnight"))

#daily steps
daily.steps <- aggregate(steps_all$steps, by=list(ID=steps_all$ID, date = steps_all$date), FUN=sum)
x <- c("ID", "date", "avg_steps")
colnames(daily.steps) <- x 

#daily steps zones
daily.steps.zones <- aggregate(steps_all$steps, by=list(ID=steps_all$ID, date = steps_all$date, timing = steps_all$timing), FUN=sum)
x <- c("ID", "date", "timing", "steps")
colnames(daily.steps.zones) <- x 
daily.steps.zones$steps <- (daily.steps.zones$steps - min(daily.steps.zones$steps))/(max(daily.steps.zones$steps) - min(daily.steps.zones$steps))

#long to wide format for zones
daily.steps.zones.wide <- dcast(daily.steps.zones, ID + date ~ timing)

#join cgm and steps data
daily.zones.data.combined = left_join(daily.CGM.zones.wide.days,daily.steps,by=c("ID"="ID", "date"="date"))
daily.zones.data.combined = left_join(daily.zones.data.combined,daily.steps.zones.wide,by=c("ID"="ID", "date"="date"))
daily.zones.data.combined <- daily.zones.data.combined[complete.cases(daily.zones.data.combined), ]


daily.zones.data.combined <- daily.zones.data.combined %>%
  dplyr::rename("steps-midnight-5am" = "midnight-5am", "steps-5am-8am" = "5am-8am", "steps-8am-11am" = "8am-11am","steps-11am-2pm" = "11am-2pm", "steps-2pm-5pm" = "2pm-5pm", "steps-5pm-9pm" = "5pm-9pm", "steps-9pm-midnight" = "9pm-midnight")


daily.zones.data.combined <- daily.zones.data.combined %>% relocate(avg_CGM, .after = date)
daily.zones.data.combined <- daily.zones.data.combined %>% relocate(avg_steps, .after = date)


diet$energy[diet$energy < 0] <- 0
diet$carb[diet$carb < 0] <- 0

diet$energy[is.na(diet$energy)] <- 0
diet$carb[is.na(diet$carb)] <- 0


diet$time_numeric <- as.numeric(diet$time1)

diet['timing'] <- NA
diet <- diet %>% relocate(timing, .before = time2)

diet$timing[diet$time_numeric > 0 & diet$time_numeric < 18000] <- "energy-midnight-5am"
diet$timing[diet$time_numeric > 18000 & diet$time_numeric < 28800] <- "energy-5am-8am"
diet$timing[diet$time_numeric > 28800 & diet$time_numeric < 39600] <- "energy-8am-11am"
diet$timing[diet$time_numeric > 39600 & diet$time_numeric < 50400] <- "energy-11am-2pm"
diet$timing[diet$time_numeric > 50400 & diet$time_numeric < 61200] <- "energy-2pm-5pm"
diet$timing[diet$time_numeric > 61200 & diet$time_numeric < 75600] <- "energy-5pm-9pm"
diet$timing[diet$time_numeric > 75600 & diet$time_numeric < 86400] <- "energy-9pm-midnight"
diet$timing <- factor(diet$timing , levels=c("energy-midnight-5am","energy-5am-8am","energy-8am-11am","energy-11am-2pm", "energy-2pm-5pm", "energy-5pm-9pm", "energy-9pm-midnight"))

#daily energy
daily.energy <- aggregate(diet$energy, by=list(ID=diet$subject.id, date = diet$date), FUN=sum)
x <- c("ID", "date", "avg_energy")
colnames(daily.energy) <- x 
daily.energy.zones <- aggregate(diet$energy, by=list(ID=diet$subject.id, date = diet$date, timing = diet$timing), FUN=sum)
x <- c("ID", "date", "timing", "energy")
colnames(daily.energy.zones) <- x 
daily.energy.zones$energy <- (daily.energy.zones$energy - min(daily.energy.zones$energy))/(max(daily.energy.zones$energy) - min(daily.energy.zones$energy))

#long to wide format for zones
daily.energy.zones.wide <- dcast(daily.energy.zones, ID + date ~ timing)
daily.energy.zones.wide[is.na(daily.energy.zones.wide)] <- 0

#join energy data with cgm and steps
daily.zones.data.combined = left_join(daily.zones.data.combined,daily.energy.zones.wide,by=c("ID"="ID", "date"="date"))
daily.zones.data.combined_v2 <- daily.zones.data.combined[!is.na(daily.zones.data.combined$avg_steps), ]
daily.zones.data.combined_v3 <- daily.zones.data.combined_v2
daily.zones.data.combined_v3[is.na(daily.zones.data.combined_v3)] <- 0

########################
#energy * steps
########################

#energy * steps for the same time-block
daily.zones.data.combined_v3$`energy.steps-midnight-5am` <- daily.zones.data.combined_v3$`energy-midnight-5am` * daily.zones.data.combined_v3$`steps-midnight-5am`
daily.zones.data.combined_v3$`energy.steps-5am-8am` <- daily.zones.data.combined_v3$`energy-5am-8am` * daily.zones.data.combined_v3$`steps-5am-8am`
daily.zones.data.combined_v3$`energy.steps-8am-11am` <- daily.zones.data.combined_v3$`energy-8am-11am` * daily.zones.data.combined_v3$`steps-8am-11am`
daily.zones.data.combined_v3$`energy.steps-11am-2pm` <- daily.zones.data.combined_v3$`energy-11am-2pm` * daily.zones.data.combined_v3$`steps-11am-2pm`
daily.zones.data.combined_v3$`energy.steps-2pm-5pm` <- daily.zones.data.combined_v3$`energy-2pm-5pm` * daily.zones.data.combined_v3$`steps-2pm-5pm`
daily.zones.data.combined_v3$`energy.steps-5pm-9pm` <- daily.zones.data.combined_v3$`energy-5pm-9pm` * daily.zones.data.combined_v3$`steps-5pm-9pm`
daily.zones.data.combined_v3$`energy.steps-9pm-midnight` <- daily.zones.data.combined_v3$`energy-9pm-midnight` * daily.zones.data.combined_v3$`steps-9pm-midnight`

#energy * steps of the previous time-block
daily.zones.data.combined_v3$`energy.steps.back-midnight-5am` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="energy.steps.back-midnight-5am" )
n2 = which( colnames(daily.zones.data.combined_v3)=="energy-midnight-5am" )
n3 = which( colnames(daily.zones.data.combined_v3)=="steps-9pm-midnight" )
daily.zones.data.combined_v3[ii,n1] <- daily.zones.data.combined_v3[ii,n2] * daily.zones.data.combined_v3[jj,n3]
daily.zones.data.combined_v3$`energy.steps.back-5am-8am` <- daily.zones.data.combined_v3$`energy-5am-8am` * daily.zones.data.combined_v3$`steps-midnight-5am`
daily.zones.data.combined_v3$`energy.steps.back-8am-11am` <- daily.zones.data.combined_v3$`energy-8am-11am` * daily.zones.data.combined_v3$`steps-5am-8am`
daily.zones.data.combined_v3$`energy.steps.back-11am-2pm` <- daily.zones.data.combined_v3$`energy-11am-2pm` * daily.zones.data.combined_v3$`steps-8am-11am`
daily.zones.data.combined_v3$`energy.steps.back-2pm-5pm` <- daily.zones.data.combined_v3$`energy-2pm-5pm` * daily.zones.data.combined_v3$`steps-11am-2pm`
daily.zones.data.combined_v3$`energy.steps.back-5pm-9pm` <- daily.zones.data.combined_v3$`energy-5pm-9pm` * daily.zones.data.combined_v3$`steps-2pm-5pm`
daily.zones.data.combined_v3$`energy.steps.back-9pm-midnight` <- daily.zones.data.combined_v3$`energy-9pm-midnight` * daily.zones.data.combined_v3$`steps-5pm-9pm`

#energy * steps of the next time-block
daily.zones.data.combined_v3$`energy.steps.fwd-midnight-5am` <- daily.zones.data.combined_v3$`energy-midnight-5am` * daily.zones.data.combined_v3$`steps-5am-8am`
daily.zones.data.combined_v3$`energy.steps.fwd-5am-8am` <- daily.zones.data.combined_v3$`energy-5am-8am` * daily.zones.data.combined_v3$`steps-8am-11am`
daily.zones.data.combined_v3$`energy.steps.fwd-8am-11am` <- daily.zones.data.combined_v3$`energy-8am-11am` * daily.zones.data.combined_v3$`steps-11am-2pm`
daily.zones.data.combined_v3$`energy.steps.fwd-11am-2pm` <- daily.zones.data.combined_v3$`energy-11am-2pm` * daily.zones.data.combined_v3$`steps-2pm-5pm`
daily.zones.data.combined_v3$`energy.steps.fwd-2pm-5pm` <- daily.zones.data.combined_v3$`energy-2pm-5pm` * daily.zones.data.combined_v3$`steps-5pm-9pm`
daily.zones.data.combined_v3$`energy.steps.fwd-5pm-9pm` <- daily.zones.data.combined_v3$`energy-5pm-9pm` * daily.zones.data.combined_v3$`steps-9pm-midnight`

daily.zones.data.combined_v3$`energy.steps.fwd-9pm-midnight` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="energy.steps.fwd-9pm-midnight" )
n2 = which( colnames(daily.zones.data.combined_v3)=="energy-9pm-midnight" )
n3 = which( colnames(daily.zones.data.combined_v3)=="steps-midnight-5am" )
daily.zones.data.combined_v3[jj,n1] <- daily.zones.data.combined_v3[jj,n2] * daily.zones.data.combined_v3[ii,n3]


###############################
#carb
###############################

diet['timing2'] <- NA
diet <- diet %>% relocate(timing2, .before = time2)

    diet$timing2[diet$time_numeric > 0 & diet$time_numeric < 18000] <- "carb-midnight-5am"
    diet$timing2[diet$time_numeric > 18000 & diet$time_numeric < 28800] <- "carb-5am-8am"
    diet$timing2[diet$time_numeric > 28800 & diet$time_numeric < 39600] <- "carb-8am-11am"
    diet$timing2[diet$time_numeric > 39600 & diet$time_numeric < 50400] <- "carb-11am-2pm"
    diet$timing2[diet$time_numeric > 50400 & diet$time_numeric < 61200] <- "carb-2pm-5pm"
    diet$timing2[diet$time_numeric > 61200 & diet$time_numeric < 75600] <- "carb-5pm-9pm"
    diet$timing2[diet$time_numeric > 75600 & diet$time_numeric < 86400] <- "carb-9pm-midnight"

    
diet$timing2 <- factor(diet$timing2 , levels=c("carb-midnight-5am","carb-5am-8am","carb-8am-11am","carb-11am-2pm", "carb-2pm-5pm", "carb-5pm-9pm", "carb-9pm-midnight"))

#daily carb
daily.carb <- aggregate(diet$carb, by=list(ID=diet$subject.id, date = diet$date), FUN=sum)
x <- c("ID", "date", "avg_carb")
colnames(daily.carb) <- x 
daily.carb.zones <- aggregate(diet$carb, by=list(ID=diet$subject.id, date = diet$date, timing = diet$timing2), FUN=sum)
x <- c("ID", "date", "timing", "carb")
colnames(daily.carb.zones) <- x 
daily.carb.zones$carb <- (daily.carb.zones$carb - min(daily.carb.zones$carb))/(max(daily.carb.zones$carb) - min(daily.carb.zones$carb))

#long to wide format for zones
daily.carb.zones.wide <- dcast(daily.carb.zones, ID + date ~ timing)
daily.carb.zones.wide[is.na(daily.carb.zones.wide)] <- 0

#join carb data with cgm, steps, energy
daily.zones.data.combined_v3 = left_join(daily.zones.data.combined_v3,daily.carb.zones.wide,by=c("ID"="ID", "date"="date"))
daily.zones.data.combined_v3[is.na(daily.zones.data.combined_v3)] <- 0

########################
#carb * steps
########################

#carb * steps for the same time-block
daily.zones.data.combined_v3$`carb.steps-midnight-5am` <- daily.zones.data.combined_v3$`carb-midnight-5am` * daily.zones.data.combined_v3$`steps-midnight-5am`
daily.zones.data.combined_v3$`carb.steps-5am-8am` <- daily.zones.data.combined_v3$`carb-5am-8am` * daily.zones.data.combined_v3$`steps-5am-8am`
daily.zones.data.combined_v3$`carb.steps-8am-11am` <- daily.zones.data.combined_v3$`carb-8am-11am` * daily.zones.data.combined_v3$`steps-8am-11am`
daily.zones.data.combined_v3$`carb.steps-11am-2pm` <- daily.zones.data.combined_v3$`carb-11am-2pm` * daily.zones.data.combined_v3$`steps-11am-2pm`
daily.zones.data.combined_v3$`carb.steps-2pm-5pm` <- daily.zones.data.combined_v3$`carb-2pm-5pm` * daily.zones.data.combined_v3$`steps-2pm-5pm`
daily.zones.data.combined_v3$`carb.steps-5pm-9pm` <- daily.zones.data.combined_v3$`carb-5pm-9pm` * daily.zones.data.combined_v3$`steps-5pm-9pm`
daily.zones.data.combined_v3$`carb.steps-9pm-midnight` <- daily.zones.data.combined_v3$`carb-9pm-midnight` * daily.zones.data.combined_v3$`steps-9pm-midnight`

#carb * steps of the previous time-block
daily.zones.data.combined_v3$`carb.steps.back-midnight-5am` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="carb.steps.back-midnight-5am" )
n2 = which( colnames(daily.zones.data.combined_v3)=="carb-midnight-5am" )
n3 = which( colnames(daily.zones.data.combined_v3)=="steps-9pm-midnight" )
daily.zones.data.combined_v3[ii,n1] <- daily.zones.data.combined_v3[ii,n2] * daily.zones.data.combined_v3[jj,n3]
daily.zones.data.combined_v3$`carb.steps.back-5am-8am` <- daily.zones.data.combined_v3$`carb-5am-8am` * daily.zones.data.combined_v3$`steps-midnight-5am`
daily.zones.data.combined_v3$`carb.steps.back-8am-11am` <- daily.zones.data.combined_v3$`carb-8am-11am` * daily.zones.data.combined_v3$`steps-5am-8am`
daily.zones.data.combined_v3$`carb.steps.back-11am-2pm` <- daily.zones.data.combined_v3$`carb-11am-2pm` * daily.zones.data.combined_v3$`steps-8am-11am`
daily.zones.data.combined_v3$`carb.steps.back-2pm-5pm` <- daily.zones.data.combined_v3$`carb-2pm-5pm` * daily.zones.data.combined_v3$`steps-11am-2pm`
daily.zones.data.combined_v3$`carb.steps.back-5pm-9pm` <- daily.zones.data.combined_v3$`carb-5pm-9pm` * daily.zones.data.combined_v3$`steps-2pm-5pm`
daily.zones.data.combined_v3$`carb.steps.back-9pm-midnight` <- daily.zones.data.combined_v3$`carb-9pm-midnight` * daily.zones.data.combined_v3$`steps-5pm-9pm`

#carb * steps of the next time-block
daily.zones.data.combined_v3$`carb.steps.fwd-midnight-5am` <- daily.zones.data.combined_v3$`carb-midnight-5am` * daily.zones.data.combined_v3$`steps-5am-8am`
daily.zones.data.combined_v3$`carb.steps.fwd-5am-8am` <- daily.zones.data.combined_v3$`carb-5am-8am` * daily.zones.data.combined_v3$`steps-8am-11am`
daily.zones.data.combined_v3$`carb.steps.fwd-8am-11am` <- daily.zones.data.combined_v3$`carb-8am-11am` * daily.zones.data.combined_v3$`steps-11am-2pm`
daily.zones.data.combined_v3$`carb.steps.fwd-11am-2pm` <- daily.zones.data.combined_v3$`carb-11am-2pm` * daily.zones.data.combined_v3$`steps-2pm-5pm`
daily.zones.data.combined_v3$`carb.steps.fwd-2pm-5pm` <- daily.zones.data.combined_v3$`carb-2pm-5pm` * daily.zones.data.combined_v3$`steps-5pm-9pm`
daily.zones.data.combined_v3$`carb.steps.fwd-5pm-9pm` <- daily.zones.data.combined_v3$`carb-5pm-9pm` * daily.zones.data.combined_v3$`steps-9pm-midnight`

daily.zones.data.combined_v3$`carb.steps.fwd-9pm-midnight` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="carb.steps.fwd-9pm-midnight" )
n2 = which( colnames(daily.zones.data.combined_v3)=="carb-9pm-midnight" )
n3 = which( colnames(daily.zones.data.combined_v3)=="steps-midnight-5am" )
daily.zones.data.combined_v3[jj,n1] <- daily.zones.data.combined_v3[jj,n2] * daily.zones.data.combined_v3[ii,n3]


########################
#activity index
########################

activity_index_all$date = mdy(activity_index_all$date)

#daily activity index
daily.AI <- aggregate(activity_index_all$normalized_activity_index, by=list(ID=activity_index_all$ID, date = activity_index_all$date), FUN=mean)
x <- c("ID", "date", "avg_AI")
colnames(daily.AI) <- x 
daily.AI.zones <- aggregate(activity_index_all$normalized_activity_index, by=list(ID=activity_index_all$ID, date = activity_index_all$date, timing = activity_index_all$timing), FUN=sum)
x <- c("ID", "date", "timing", "AI")
colnames(daily.AI.zones) <- x 
daily.AI.zones$AI <- (daily.AI.zones$AI - min(daily.AI.zones$AI))/(max(daily.AI.zones$AI) - min(daily.AI.zones$AI))
daily.AI.zones$timing <- factor(daily.AI.zones$timing , levels=c("midnight-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-midnight"))

#long to wide format for zones
daily.AI.zones.wide <- dcast(daily.AI.zones, ID + date ~ timing)
daily.AI.zones.wide[is.na(daily.AI.zones.wide)] <- 0

#join activity index with previous data
daily.zones.data.combined_v3 = left_join(daily.zones.data.combined_v3,daily.AI,by=c("ID"="ID", "date"="date"))
daily.zones.data.combined_v3 = left_join(daily.zones.data.combined_v3,daily.AI.zones.wide,by=c("ID"="ID", "date"="date"))
daily.zones.data.combined_v3 <- daily.zones.data.combined_v3 %>%
  dplyr::rename("AI-midnight-5am" = "midnight-5am", "AI-5am-8am" = "5am-8am", "AI-8am-11am" = "8am-11am","AI-11am-2pm" = "11am-2pm", "AI-2pm-5pm" = "2pm-5pm", "AI-5pm-9pm" = "5pm-9pm", "AI-9pm-midnight" = "9pm-midnight")
daily.zones.data.combined_v3 <- daily.zones.data.combined_v3 %>% relocate(avg_AI, .after = date)


########################
#energy * AI
########################

#energy * AI for the same time-block
daily.zones.data.combined_v3$`energy.AI-midnight-5am` <- daily.zones.data.combined_v3$`energy-midnight-5am` * daily.zones.data.combined_v3$`AI-midnight-5am`
daily.zones.data.combined_v3$`energy.AI-5am-8am` <- daily.zones.data.combined_v3$`energy-5am-8am` * daily.zones.data.combined_v3$`AI-5am-8am`
daily.zones.data.combined_v3$`energy.AI-8am-11am` <- daily.zones.data.combined_v3$`energy-8am-11am` * daily.zones.data.combined_v3$`AI-8am-11am`
daily.zones.data.combined_v3$`energy.AI-11am-2pm` <- daily.zones.data.combined_v3$`energy-11am-2pm` * daily.zones.data.combined_v3$`AI-11am-2pm`
daily.zones.data.combined_v3$`energy.AI-2pm-5pm` <- daily.zones.data.combined_v3$`energy-2pm-5pm` * daily.zones.data.combined_v3$`AI-2pm-5pm`
daily.zones.data.combined_v3$`energy.AI-5pm-9pm` <- daily.zones.data.combined_v3$`energy-5pm-9pm` * daily.zones.data.combined_v3$`AI-5pm-9pm`
daily.zones.data.combined_v3$`energy.AI-9pm-midnight` <- daily.zones.data.combined_v3$`energy-9pm-midnight` * daily.zones.data.combined_v3$`AI-9pm-midnight`

#energy * AI of the previous time-block
daily.zones.data.combined_v3$`energy.AI.back-midnight-5am` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="energy.AI.back-midnight-5am" )
n2 = which( colnames(daily.zones.data.combined_v3)=="energy-midnight-5am" )
n3 = which( colnames(daily.zones.data.combined_v3)=="AI-9pm-midnight" )
daily.zones.data.combined_v3[ii,n1] <- daily.zones.data.combined_v3[ii,n2] * daily.zones.data.combined_v3[jj,n3]
daily.zones.data.combined_v3$`energy.AI.back-5am-8am` <- daily.zones.data.combined_v3$`energy-5am-8am` * daily.zones.data.combined_v3$`AI-midnight-5am`
daily.zones.data.combined_v3$`energy.AI.back-8am-11am` <- daily.zones.data.combined_v3$`energy-8am-11am` * daily.zones.data.combined_v3$`AI-5am-8am`
daily.zones.data.combined_v3$`energy.AI.back-11am-2pm` <- daily.zones.data.combined_v3$`energy-11am-2pm` * daily.zones.data.combined_v3$`AI-8am-11am`
daily.zones.data.combined_v3$`energy.AI.back-2pm-5pm` <- daily.zones.data.combined_v3$`energy-2pm-5pm` * daily.zones.data.combined_v3$`AI-11am-2pm`
daily.zones.data.combined_v3$`energy.AI.back-5pm-9pm` <- daily.zones.data.combined_v3$`energy-5pm-9pm` * daily.zones.data.combined_v3$`AI-2pm-5pm`
daily.zones.data.combined_v3$`energy.AI.back-9pm-midnight` <- daily.zones.data.combined_v3$`energy-9pm-midnight` * daily.zones.data.combined_v3$`AI-5pm-9pm`

#energy * AI of the next time-block
daily.zones.data.combined_v3$`energy.AI.fwd-midnight-5am` <- daily.zones.data.combined_v3$`energy-midnight-5am` * daily.zones.data.combined_v3$`AI-5am-8am`
daily.zones.data.combined_v3$`energy.AI.fwd-5am-8am` <- daily.zones.data.combined_v3$`energy-5am-8am` * daily.zones.data.combined_v3$`AI-8am-11am`
daily.zones.data.combined_v3$`energy.AI.fwd-8am-11am` <- daily.zones.data.combined_v3$`energy-8am-11am` * daily.zones.data.combined_v3$`AI-11am-2pm`
daily.zones.data.combined_v3$`energy.AI.fwd-11am-2pm` <- daily.zones.data.combined_v3$`energy-11am-2pm` * daily.zones.data.combined_v3$`AI-2pm-5pm`
daily.zones.data.combined_v3$`energy.AI.fwd-2pm-5pm` <- daily.zones.data.combined_v3$`energy-2pm-5pm` * daily.zones.data.combined_v3$`AI-5pm-9pm`
daily.zones.data.combined_v3$`energy.AI.fwd-5pm-9pm` <- daily.zones.data.combined_v3$`energy-5pm-9pm` * daily.zones.data.combined_v3$`AI-9pm-midnight`

daily.zones.data.combined_v3$`energy.AI.fwd-9pm-midnight` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="energy.AI.fwd-9pm-midnight" )
n2 = which( colnames(daily.zones.data.combined_v3)=="energy-9pm-midnight" )
n3 = which( colnames(daily.zones.data.combined_v3)=="AI-midnight-5am" )
daily.zones.data.combined_v3[jj,n1] <- daily.zones.data.combined_v3[jj,n2] * daily.zones.data.combined_v3[ii,n3]

########################
#carb * AI
########################

#carb * AI for the same time-block
daily.zones.data.combined_v3$`carb.AI-midnight-5am` <- daily.zones.data.combined_v3$`carb-midnight-5am` * daily.zones.data.combined_v3$`AI-midnight-5am`
daily.zones.data.combined_v3$`carb.AI-5am-8am` <- daily.zones.data.combined_v3$`carb-5am-8am` * daily.zones.data.combined_v3$`AI-5am-8am`
daily.zones.data.combined_v3$`carb.AI-8am-11am` <- daily.zones.data.combined_v3$`carb-8am-11am` * daily.zones.data.combined_v3$`AI-8am-11am`
daily.zones.data.combined_v3$`carb.AI-11am-2pm` <- daily.zones.data.combined_v3$`carb-11am-2pm` * daily.zones.data.combined_v3$`AI-11am-2pm`
daily.zones.data.combined_v3$`carb.AI-2pm-5pm` <- daily.zones.data.combined_v3$`carb-2pm-5pm` * daily.zones.data.combined_v3$`AI-2pm-5pm`
daily.zones.data.combined_v3$`carb.AI-5pm-9pm` <- daily.zones.data.combined_v3$`carb-5pm-9pm` * daily.zones.data.combined_v3$`AI-5pm-9pm`
daily.zones.data.combined_v3$`carb.AI-9pm-midnight` <- daily.zones.data.combined_v3$`carb-9pm-midnight` * daily.zones.data.combined_v3$`AI-9pm-midnight`

#carb * AI of the previous time-block
daily.zones.data.combined_v3$`carb.AI.back-midnight-5am` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="carb.AI.back-midnight-5am" )
n2 = which( colnames(daily.zones.data.combined_v3)=="carb-midnight-5am" )
n3 = which( colnames(daily.zones.data.combined_v3)=="AI-9pm-midnight" )
daily.zones.data.combined_v3[ii,n1] <- daily.zones.data.combined_v3[ii,n2] * daily.zones.data.combined_v3[jj,n3]
daily.zones.data.combined_v3$`carb.AI.back-5am-8am` <- daily.zones.data.combined_v3$`carb-5am-8am` * daily.zones.data.combined_v3$`AI-midnight-5am`
daily.zones.data.combined_v3$`carb.AI.back-8am-11am` <- daily.zones.data.combined_v3$`carb-8am-11am` * daily.zones.data.combined_v3$`AI-5am-8am`
daily.zones.data.combined_v3$`carb.AI.back-11am-2pm` <- daily.zones.data.combined_v3$`carb-11am-2pm` * daily.zones.data.combined_v3$`AI-8am-11am`
daily.zones.data.combined_v3$`carb.AI.back-2pm-5pm` <- daily.zones.data.combined_v3$`carb-2pm-5pm` * daily.zones.data.combined_v3$`AI-11am-2pm`
daily.zones.data.combined_v3$`carb.AI.back-5pm-9pm` <- daily.zones.data.combined_v3$`carb-5pm-9pm` * daily.zones.data.combined_v3$`AI-2pm-5pm`
daily.zones.data.combined_v3$`carb.AI.back-9pm-midnight` <- daily.zones.data.combined_v3$`carb-9pm-midnight` * daily.zones.data.combined_v3$`AI-5pm-9pm`

#carb * AI of the next time-block
daily.zones.data.combined_v3$`carb.AI.fwd-midnight-5am` <- daily.zones.data.combined_v3$`carb-midnight-5am` * daily.zones.data.combined_v3$`AI-5am-8am`
daily.zones.data.combined_v3$`carb.AI.fwd-5am-8am` <- daily.zones.data.combined_v3$`carb-5am-8am` * daily.zones.data.combined_v3$`AI-8am-11am`
daily.zones.data.combined_v3$`carb.AI.fwd-8am-11am` <- daily.zones.data.combined_v3$`carb-8am-11am` * daily.zones.data.combined_v3$`AI-11am-2pm`
daily.zones.data.combined_v3$`carb.AI.fwd-11am-2pm` <- daily.zones.data.combined_v3$`carb-11am-2pm` * daily.zones.data.combined_v3$`AI-2pm-5pm`
daily.zones.data.combined_v3$`carb.AI.fwd-2pm-5pm` <- daily.zones.data.combined_v3$`carb-2pm-5pm` * daily.zones.data.combined_v3$`AI-5pm-9pm`
daily.zones.data.combined_v3$`carb.AI.fwd-5pm-9pm` <- daily.zones.data.combined_v3$`carb-5pm-9pm` * daily.zones.data.combined_v3$`AI-9pm-midnight`

daily.zones.data.combined_v3$`carb.AI.fwd-9pm-midnight` <- 0
ii <- 2:nrow(daily.zones.data.combined_v3)
jj <- 1:(nrow(daily.zones.data.combined_v3)-1)
n1 = which( colnames(daily.zones.data.combined_v3)=="carb.AI.fwd-9pm-midnight" )
n2 = which( colnames(daily.zones.data.combined_v3)=="carb-9pm-midnight" )
n3 = which( colnames(daily.zones.data.combined_v3)=="AI-midnight-5am" )
daily.zones.data.combined_v3[jj,n1] <- daily.zones.data.combined_v3[jj,n2] * daily.zones.data.combined_v3[ii,n3]

#join meta data with previous data
daily.zones.data.combined_v3 = left_join(daily.zones.data.combined_v3,meta.lab.v2,by=c("ID"="subject.id"))


############################
#sleep
############################
diet_timing$date <- as.Date(diet_timing$first.food.time)
sleep$time.numeric <- as.numeric(sleep$time)
sleep <- sleep %>% relocate(time.numeric, .after = time)
sleep$wake.time.numeric <- as.numeric(as_hms(anytime(sleep$wake.time)))
sleep <- sleep %>% relocate(wake.time.numeric, .before = wake.time)
steps_all = left_join(steps_all,sleep,by=c("ID"="subject.id", "date"="date"))
steps_all = left_join(steps_all,diet_timing,by=c("ID"="subject.id", "date"="date"))
steps_all$first.food.time.2 <- as_hms(anytime(steps_all$first.food.time.unix))
steps_all$first.food.time.numeric <- as.numeric(steps_all$first.food.time.2)
steps_all$last.food.time.2 <- as_hms(anytime(steps_all$last.food.time.unix))
steps_all$last.food.time.numeric <- as.numeric(steps_all$last.food.time.2)

steps_pre_sleep <- data.frame(ID = character(),
                              date = Date(),
                              steps_1h = numeric(),
                              steps_2h = numeric(),
                              steps_3h = numeric(),
                              steps_4h = numeric(),
                              steps_last_food_to_sleep = numeric(),
                              steps_last_food_to_sleep_per_min = numeric(),
                              bed_time = numeric())


i=0

for (u in unique(steps_all$ID)) 
{
  temp <- steps_all %>% subset(ID == u)
  for (v in unique(temp$date)) 
  {
    temp2 <- temp %>% subset(date == v)
    if (is.na(temp2[1,20]) | temp2[1,20] < 72000) {next}
    i=i+1
    steps_pre_sleep[i,1] <- u
    steps_pre_sleep[i,2] <- as.Date(v, origin="1970-01-01")
    steps_pre_sleep[i,3] <- sum(temp2$steps[temp2$time_numeric > (temp2$time.numeric - 3600) & temp2$time_numeric < temp2$time.numeric])
    steps_pre_sleep[i,4] <- sum(temp2$steps[temp2$time_numeric > (temp2$time.numeric - 3600*2) & temp2$time_numeric < temp2$time.numeric])
    steps_pre_sleep[i,5] <- sum(temp2$steps[temp2$time_numeric > (temp2$time.numeric - 3600*3) & temp2$time_numeric < temp2$time.numeric])
    steps_pre_sleep[i,6] <- sum(temp2$steps[temp2$time_numeric > (temp2$time.numeric - 3600*4) & temp2$time_numeric < temp2$time.numeric])
    steps_pre_sleep[i,7] <- sum(temp2$steps[temp2$time_numeric > (temp2$last.food.time.numeric) & temp2$time_numeric < temp2$time.numeric])
    steps_pre_sleep[i,8] <- sum(temp2$steps[temp2$time_numeric > (temp2$last.food.time.numeric) & temp2$time_numeric < temp2$time.numeric])/(temp2$time.numeric[1] - temp2$last.food.time.numeric[1])*60
    steps_pre_sleep[i,9] <- temp2[1,20]
  }
 }

steps_pre_sleep$bed_time <- as_hms(steps_pre_sleep$bed_time)
steps_pre_sleep = left_join(steps_pre_sleep,daily.CGM,by=c("ID"="ID", "date"="date"))
steps_pre_sleep <- steps_pre_sleep[complete.cases(steps_pre_sleep), ]

temp <- steps_pre_sleep$avg_CGM
temp <- temp[-1]
temp <- c(temp, NA)

steps_pre_sleep$avg_CGM_next <- temp
steps_pre_sleep <- steps_pre_sleep[-nrow(steps_pre_sleep),]


###################################
#post-wake steps
###################################

cgm = left_join(cgm,sleep,by=c("ID"="subject.id", "date"="date"))
cgm$wake.time.numeric <- as.numeric(as_hms(anytime(cgm$wake.time)))
cgm <- cgm %>% relocate(wake.time.numeric, .before = wake.time)
cgm.post.wake <- cgm %>% subset(time_numeric > wake.time.numeric)

daily.cgm.post.wake <- aggregate(cgm.post.wake$CGM, by=list(ID=cgm.post.wake$ID, date = cgm.post.wake$date), FUN=mean)
x <- c("ID", "date", "avg_CGM_post_wake")
colnames(daily.cgm.post.wake) <- x

steps_all$wake.time.numeric <- as.numeric(as_hms(anytime(steps_all$wake.time)))
steps_all <- steps_all %>% relocate(wake.time.numeric, .before = wake.time)

steps_post_sleep <- data.frame(ID = character(),
                              date = Date(),
                              steps_1h = numeric(),
                              steps_2h = numeric(),
                              steps_3h = numeric(),
                              steps_4h = numeric(),
                              steps_wake_to_meal = numeric(),
                              steps_wake_to_meal_per_min = numeric(),
                              wake_time = numeric(),
                              wake_time_unix = numeric())


i=0

for (u in unique(steps_all$ID)) 
{
  temp <- steps_all %>% subset(ID == u)
  for (v in unique(temp$date)) 
  {
    temp2 <- temp %>% subset(date == v)
    if (is.na(temp2[1,37]) | temp2[1,37] < 14400 | temp2[1,37] > 39600) {next}
    i=i+1
    steps_post_sleep[i,1] <- u
    steps_post_sleep[i,2] <- as.Date(v, origin="1970-01-01")
    steps_post_sleep[i,3] <- sum(temp2$steps[temp2$time_numeric < (temp2$wake.time.numeric + 3600) & temp2$time_numeric > temp2$wake.time.numeric])
    steps_post_sleep[i,4] <- sum(temp2$steps[temp2$time_numeric < (temp2$wake.time.numeric + 3600*2) & temp2$time_numeric > temp2$wake.time.numeric])
    steps_post_sleep[i,5] <- sum(temp2$steps[temp2$time_numeric < (temp2$wake.time.numeric + 3600*3) & temp2$time_numeric > temp2$wake.time.numeric])
    steps_post_sleep[i,6] <- sum(temp2$steps[temp2$time_numeric < (temp2$wake.time.numeric + 3600*4) & temp2$time_numeric > temp2$wake.time.numeric])
    steps_post_sleep[i,7] <- sum(temp2$steps[temp2$time_numeric < (temp2$first.food.time.numeric) & temp2$time_numeric > temp2$wake.time.numeric])
    steps_post_sleep[i,8] <- sum(temp2$steps[temp2$time_numeric < (temp2$first.food.time.numeric) & temp2$time_numeric > temp2$wake.time.numeric])/(temp2$first.food.time.numeric[1] - temp2$wake.time.numeric[1])*60
    steps_post_sleep[i,9] <- temp2[1,37]
    steps_post_sleep[i,10] <- temp2[1,38]
  }
 }

steps_post_sleep$wake_time <- as_hms(steps_post_sleep$wake_time)
steps_post_sleep$wake_time_numeric <- as.numeric(steps_post_sleep$wake_time)
steps_post_sleep = left_join(steps_post_sleep,daily.cgm.post.wake,by=c("ID"="ID", "date"="date"))
steps_post_sleep <- steps_post_sleep[complete.cases(steps_post_sleep), ]


diet = left_join(diet,sleep,by=c("subject.id"="subject.id", "date"="date"))

diet['timing.sleep'] <- NA
diet <- diet %>% relocate(timing.sleep, .before = time2)

diet$timing.sleep[diet$time_numeric > (diet$time.numeric - 3600) & diet$time_numeric < diet$time.numeric] <- "1h_pre_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$time.numeric - 2*3600) & diet$time_numeric < (diet$time.numeric - 3600)] <- "2h_pre_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$time.numeric - 3*3600) & diet$time_numeric < (diet$time.numeric - 2*3600)] <- "3h_pre_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$time.numeric - 4*3600) & diet$time_numeric < (diet$time.numeric - 3*3600)] <- "4h_pre_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$wake.time.numeric) & diet$time_numeric < (diet$wake.time.numeric + 3600)] <- "1h_post_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$wake.time.numeric + 3600) & diet$time_numeric < (diet$wake.time.numeric + 2*3600)] <- "2h_post_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$wake.time.numeric + 2*3600) & diet$time_numeric < (diet$wake.time.numeric + 3*3600)] <- "3h_post_sleep_energy"
diet$timing.sleep[diet$time_numeric > (diet$wake.time.numeric + 3*3600) & diet$time_numeric < (diet$wake.time.numeric + 4*3600)] <- "4h_post_sleep_energy"

diet$timing.sleep <- factor(diet$timing.sleep , levels=c("1h_pre_sleep_energy","2h_pre_sleep_energy","3h_pre_sleep_energy","4h_pre_sleep_energy","1h_post_sleep_energy","2h_post_sleep_energy","3h_post_sleep_energy","4h_post_sleep_energy"))

diet.pre.post.sleep <- aggregate(diet$energy, by=list(ID=diet$subject.id, date = diet$date, timing.sleep = diet$timing.sleep), FUN=sum)
x <- c("ID", "date", "timing.sleep", "energy")
colnames(diet.pre.post.sleep) <- x 

#long to wide format for zones
diet.pre.post.sleep.wide <- dcast(diet.pre.post.sleep, ID + date ~ timing.sleep)
diet.pre.post.sleep.wide[is.na(diet.pre.post.sleep.wide)] <- 0
diet.pre.post.sleep.wide$`4h_pre_sleep_energy` <-  diet.pre.post.sleep.wide$`4h_pre_sleep_energy` + diet.pre.post.sleep.wide$`3h_pre_sleep_energy` + diet.pre.post.sleep.wide$`2h_pre_sleep_energy` + diet.pre.post.sleep.wide$`1h_pre_sleep_energy`
diet.pre.post.sleep.wide$`3h_pre_sleep_energy` <-  diet.pre.post.sleep.wide$`3h_pre_sleep_energy` + diet.pre.post.sleep.wide$`2h_pre_sleep_energy` + diet.pre.post.sleep.wide$`1h_pre_sleep_energy`
diet.pre.post.sleep.wide$`2h_pre_sleep_energy` <-  diet.pre.post.sleep.wide$`2h_pre_sleep_energy` + diet.pre.post.sleep.wide$`1h_pre_sleep_energy`
diet.pre.post.sleep.wide$`4h_post_sleep_energy` <-  diet.pre.post.sleep.wide$`4h_post_sleep_energy` + diet.pre.post.sleep.wide$`3h_post_sleep_energy` + diet.pre.post.sleep.wide$`2h_post_sleep_energy` + diet.pre.post.sleep.wide$`1h_post_sleep_energy`
diet.pre.post.sleep.wide$`3h_post_sleep_energy` <-  diet.pre.post.sleep.wide$`3h_post_sleep_energy` + diet.pre.post.sleep.wide$`2h_post_sleep_energy` + diet.pre.post.sleep.wide$`1h_post_sleep_energy`
diet.pre.post.sleep.wide$`2h_post_sleep_energy` <-  diet.pre.post.sleep.wide$`2h_post_sleep_energy` + diet.pre.post.sleep.wide$`1h_post_sleep_energy`


steps_pre_sleep = left_join(steps_pre_sleep,diet.pre.post.sleep.wide,by=c("ID"="ID", "date"="date"))
steps_pre_sleep_v2<- steps_pre_sleep
steps_pre_sleep_v2$`1h_pre_sleep_energy`[steps_pre_sleep_v2$`1h_pre_sleep_energy` > 0] <- 1
steps_pre_sleep_v2$`1h_pre_sleep_energy`[steps_pre_sleep_v2$`1h_pre_sleep_energy` == 0] <- 0
steps_pre_sleep_v2$`2h_pre_sleep_energy`[steps_pre_sleep_v2$`2h_pre_sleep_energy` > 0] <- 1
steps_pre_sleep_v2$`2h_pre_sleep_energy`[steps_pre_sleep_v2$`2h_pre_sleep_energy` == 0] <- 0
steps_pre_sleep_v2$`3h_pre_sleep_energy`[steps_pre_sleep_v2$`3h_pre_sleep_energy` > 0] <- 1
steps_pre_sleep_v2$`3h_pre_sleep_energy`[steps_pre_sleep_v2$`3h_pre_sleep_energy` == 0] <- 0
steps_pre_sleep_v2$`4h_pre_sleep_energy`[steps_pre_sleep_v2$`4h_pre_sleep_energy` > 0] <- 1
steps_pre_sleep_v2$`4h_pre_sleep_energy`[steps_pre_sleep_v2$`4h_pre_sleep_energy` == 0] <- 0
steps_pre_sleep_v2 <- steps_pre_sleep_v2[complete.cases(steps_pre_sleep_v2), ]
steps_pre_sleep_v2 = left_join(steps_pre_sleep_v2,meta.lab.v2,by=c("ID"="subject.id"))
steps_pre_sleep <- steps_pre_sleep[complete.cases(steps_pre_sleep), ]
steps_pre_sleep = left_join(steps_pre_sleep,meta.lab.v2,by=c("ID"="subject.id"))

steps_post_sleep = left_join(steps_post_sleep,diet.pre.post.sleep.wide,by=c("ID"="ID", "date"="date"))
steps_post_sleep_v2<- steps_post_sleep
steps_post_sleep_v2$`1h_post_sleep_energy`[steps_post_sleep_v2$`1h_post_sleep_energy` > 0] <- 1
steps_post_sleep_v2$`1h_post_sleep_energy`[steps_post_sleep_v2$`1h_post_sleep_energy` == 0] <- 0
steps_post_sleep_v2$`2h_post_sleep_energy`[steps_post_sleep_v2$`2h_post_sleep_energy` > 0] <- 1
steps_post_sleep_v2$`2h_post_sleep_energy`[steps_post_sleep_v2$`2h_post_sleep_energy` == 0] <- 0
steps_post_sleep_v2$`3h_post_sleep_energy`[steps_post_sleep_v2$`3h_post_sleep_energy` > 0] <- 1
steps_post_sleep_v2$`3h_post_sleep_energy`[steps_post_sleep_v2$`3h_post_sleep_energy` == 0] <- 0
steps_post_sleep_v2$`4h_post_sleep_energy`[steps_post_sleep_v2$`4h_post_sleep_energy` > 0] <- 1
steps_post_sleep_v2$`4h_post_sleep_energy`[steps_post_sleep_v2$`4h_post_sleep_energy` == 0] <- 0
steps_post_sleep_v2 <- steps_post_sleep_v2[complete.cases(steps_post_sleep_v2), ]
steps_post_sleep_v2 = left_join(steps_post_sleep_v2,meta.lab.v2,by=c("ID"="subject.id"))
steps_post_sleep <- steps_post_sleep[complete.cases(steps_post_sleep), ]
steps_post_sleep = left_join(steps_post_sleep,meta.lab.v2,by=c("ID"="subject.id"))

#daily steps avg
daily.steps.avg <- aggregate(daily.steps$avg_steps, by=list(ID=daily.steps$ID), FUN=mean)
x <- c("ID", "daily_steps")
colnames(daily.steps.avg) <- x 

#daily AI avg
daily.AI.avg <- aggregate(daily.AI$avg_AI, by=list(ID=daily.AI$ID), FUN=mean)
x <- c("ID", "daily_activity_index")
colnames(daily.AI.avg) <- x 

#avg steps pre-sleep
temp1 <- aggregate(steps_pre_sleep$steps_1h, by=list(ID=steps_pre_sleep$ID), FUN=mean)
temp2 <- aggregate(steps_pre_sleep$steps_2h, by=list(ID=steps_pre_sleep$ID), FUN=mean)
temp3 <- aggregate(steps_pre_sleep$steps_3h, by=list(ID=steps_pre_sleep$ID), FUN=mean)
temp4 <- aggregate(steps_pre_sleep$steps_4h, by=list(ID=steps_pre_sleep$ID), FUN=mean)
temp5 <- aggregate(steps_pre_sleep$steps_last_food_to_sleep, by=list(ID=steps_pre_sleep$ID), FUN=mean, na.rm=TRUE)
temp6 <- aggregate(steps_pre_sleep$steps_last_food_to_sleep_per_min, by=list(ID=steps_pre_sleep$ID), FUN=mean, na.rm=TRUE)
temp5 <- temp5[complete.cases(temp5), ]
temp6 <- temp6[complete.cases(temp6), ]

avg.pre.sleep.steps = left_join(temp1,temp2,by=c("ID"="ID"))
avg.pre.sleep.steps = left_join(avg.pre.sleep.steps,temp3,by=c("ID"="ID"))
avg.pre.sleep.steps = left_join(avg.pre.sleep.steps,temp4,by=c("ID"="ID"))
avg.pre.sleep.steps = left_join(avg.pre.sleep.steps,temp5,by=c("ID"="ID"))
avg.pre.sleep.steps = left_join(avg.pre.sleep.steps,temp6,by=c("ID"="ID"))

x <- c("ID", "1h_pre_sleep_steps", "2h_pre_sleep_steps", "3h_pre_sleep_steps", "4h_pre_sleep_steps", "last_food_to_sleep_steps", "last_food_to_sleep_steps_per_min")
colnames(avg.pre.sleep.steps) <- x 

#avg steps post-wake
temp1 <- aggregate(steps_post_sleep$steps_1h, by=list(ID=steps_post_sleep$ID), FUN=mean)
temp2 <- aggregate(steps_post_sleep$steps_2h, by=list(ID=steps_post_sleep$ID), FUN=mean)
temp3 <- aggregate(steps_post_sleep$steps_3h, by=list(ID=steps_post_sleep$ID), FUN=mean)
temp4 <- aggregate(steps_post_sleep$steps_4h, by=list(ID=steps_post_sleep$ID), FUN=mean)
temp5 <- aggregate(steps_post_sleep$steps_wake_to_meal, by=list(ID=steps_post_sleep$ID), FUN=mean, na.rm=TRUE)
temp6 <- aggregate(steps_post_sleep$steps_wake_to_meal_per_min, by=list(ID=steps_post_sleep$ID), FUN=mean, na.rm=TRUE)
temp5 <- temp5[complete.cases(temp5), ]
temp6 <- temp6[complete.cases(temp6), ]

avg.post.wake.steps = left_join(temp1,temp2,by=c("ID"="ID"))
avg.post.wake.steps = left_join(avg.post.wake.steps,temp3,by=c("ID"="ID"))
avg.post.wake.steps = left_join(avg.post.wake.steps,temp4,by=c("ID"="ID"))
avg.post.wake.steps = left_join(avg.post.wake.steps,temp5,by=c("ID"="ID"))
avg.post.wake.steps = left_join(avg.post.wake.steps,temp6,by=c("ID"="ID"))

x <- c("ID", "1h_post_sleep_steps", "2h_post_sleep_steps", "3h_post_sleep_steps", "4h_post_sleep_steps", "wake_to_first_food_steps", "wake_to_first_food_steps_per_min")
colnames(avg.post.wake.steps) <- x 


steps_pre_sleep_sub <- steps_pre_sleep
steps_pre_sleep_sub <- steps_pre_sleep_sub %>%
  dplyr::rename("1h_pre_sleep_steps" = "steps_1h", "2h_pre_sleep_steps" = "steps_2h", "3h_pre_sleep_steps" = "steps_3h", "4h_pre_sleep_steps" = "steps_4h", "last_food_to_sleep_steps" = "steps_last_food_to_sleep")
steps_pre_sleep_sub <- steps_pre_sleep_sub[,1:7]


steps_post_sleep_sub <- steps_post_sleep
steps_post_sleep_sub <- steps_post_sleep_sub %>%
  dplyr::rename("1h_post_sleep_steps" = "steps_1h", "2h_post_sleep_steps" = "steps_2h", "3h_post_sleep_steps" = "steps_3h", "4h_post_sleep_steps" = "steps_4h", "wake_food_to_sleep_steps" = "steps_wake_to_meal")
steps_post_sleep_sub <- steps_post_sleep_sub[,1:7]


######################################
#Physical activity features
######################################

hourly.steps <- aggregate(steps_all$steps, by=list(ID=steps_all$ID, day_number_CGM = steps_all$day_number_CGM, date = steps_all$date, hour = steps_all$hour), FUN=sum)
x <- c("ID", "day_number_CGM", "date", "hour","hourly.steps")
colnames(hourly.steps) <- x
hourly.steps['active_hour'] <- NA
hourly.steps$active_hour[hourly.steps$hourly.steps >= 250] <- 1
hourly.steps$active_hour[hourly.steps$hourly.steps < 250] <- 0


active.hours <- aggregate(hourly.steps$active_hour, by=list(ID=hourly.steps$ID, day_number_CGM = hourly.steps$day_number_CGM, date = hourly.steps$date), FUN=sum)
x <- c("ID", "day_number_CGM", "date", "active_hours")
colnames(active.hours) <- x
active.hours.avg <- aggregate(active.hours$active_hours, by=list(ID=active.hours$ID), FUN=mean)


moving <- data.frame(
  ID=character(),
  date=Date(),
  timing=character(),
  sedentary.min=numeric(),
  move.min=numeric(),
  move.over.sed=numeric())


m=1
for (u in unique(steps_all$ID))
{
  temp0 <- steps_all %>% subset(ID == u)
  for (n in unique(temp0$date))
    {
      temp <- temp0 %>% subset(date == n)
      temp = temp[!duplicated(temp$date_time),]
      for (t in unique(temp$timing))
        {
          temp1 <- temp %>% subset(timing == t)
          temp2 <- temp1 %>% subset(steps == 0)
          moving[m,1] <- u #ID
          moving[m,2] <- as.Date(n, origin="1970-01-01") #date
          moving[m,3] <- t #timing
          moving[m,4] <- nrow(temp2) #sedentary mins
          moving[m,5] <- nrow(temp1) - nrow(temp2) #moving mins
          moving[m,6] <- (nrow(temp1) - nrow(temp2))/nrow(temp2) #ratio of moving/sitting
          m=m+1
        }
    }
 }
    

moving <- moving %>% subset(move.min > 0 & sedentary.min > 0)


#daily avg active hours
active.hours.mean.sd <- ddply(active.hours, .(ID), summarize, 
                  active.hours.avg = mean(active_hours, na.rm=TRUE),
                  active.hours.sd = sd(active_hours, na.rm=TRUE))
active.hours.mean.sd$active.hours.cv <- active.hours.mean.sd$active.hours.sd/ active.hours.mean.sd$active.hours.avg

#moving and sedentary daily avg
daily.moving <- aggregate(moving$move.min, by=list(ID=moving$ID, date = moving$date), FUN=sum)
x <- c("ID", "date", "move.min")
colnames(daily.moving) <- x 

daily.sed<- aggregate(moving$sedentary.min, by=list(ID=moving$ID, date = moving$date), FUN=sum)
x <- c("ID", "date", "sedentary.min")
colnames(daily.sed) <- x 

daily.move.over.sed<- aggregate(moving$move.over.sed, by=list(ID=moving$ID, date = moving$date), FUN=mean)
x <- c("ID", "date", "move.over.sed")
colnames(daily.move.over.sed) <- x 

daily.moving.avg <- aggregate(daily.moving$move.min, by=list(ID=daily.moving$ID), FUN=mean)
daily.sed.avg <- aggregate(daily.sed$sedentary.min, by=list(ID=daily.sed$ID), FUN=mean)
daily.move.sed.avg = left_join(daily.move.over.sed,daily.moving.avg,by=c("ID"="ID"))
daily.move.sed.avg = left_join(daily.move.sed.avg,daily.sed.avg,by=c("ID"="ID"))
daily.move.sed.active.avg = left_join(daily.move.sed.avg,active.hours.avg,by=c("ID"="ID"))

x <- c("ID", "move.over.sed", "move.mins", "sedentary.mins", "num.active.hours")
colnames(daily.move.sed.active.avg) <- x 

x <- c("ID", "date", "sedentary.min")
colnames(daily.sed) <- x 

#daily avg moving mins
daily.moving.mean.sd <- ddply(daily.moving, .(ID), summarize, 
                  move.min.avg = mean(move.min, na.rm=TRUE),
                  move.min.sd = sd(move.min, na.rm=TRUE))

daily.moving.mean.sd$move.min.cv <- daily.moving.mean.sd$move.min.sd / daily.moving.mean.sd$move.min.avg

#daily avg sedentary mins
daily.sed.mean.sd <- ddply(daily.sed, .(ID), summarize, 
                  sed.min.avg = mean(sedentary.min, na.rm=TRUE),
                  sed.min.sd = sd(sedentary.min, na.rm=TRUE))

daily.sed.mean.sd$sed.min.cv <- daily.sed.mean.sd$sed.min.sd / daily.sed.mean.sd$sed.min.avg

daily.move.sed = left_join(daily.moving,daily.sed,by=c("ID"="ID", "date"="date"))
daily.move.sed$move.plus.sed <- daily.move.sed$move.min + daily.move.sed$sedentary.min
daily.move.sed$move.over.sed <- daily.move.sed$move.min / daily.move.sed$sedentary.min


#daily avg moving/sedentary 
daily.move.sed.ratio.mean.sd <- ddply(daily.move.over.sed, .(ID), summarize, 
                  move.sed.ratio.avg = mean(move.over.sed, na.rm=TRUE),
                  move.sed.ratio.sd = sd(move.over.sed, na.rm=TRUE))

daily.move.sed.ratio.mean.sd$move.sed.ratio.cv <- daily.move.sed.ratio.mean.sd$move.sed.ratio.sd / daily.move.sed.ratio.mean.sd$move.sed.ratio.avg


daily.move.sed.all.mean.sd <- left_join(daily.moving.mean.sd,daily.sed.mean.sd,by=c("ID"="ID"))
daily.move.sed.all.mean.sd <- left_join(daily.move.sed.all.mean.sd,daily.move.sed.ratio.mean.sd,by=c("ID"="ID"))

#join all daily physical activity features
PA_features_days = left_join(daily.steps,daily.AI,by=c("ID"="ID", "date"="date"))
PA_features_days = left_join(PA_features_days,steps_pre_sleep_sub,by=c("ID"="ID", "date"="date"))
PA_features_days = left_join(PA_features_days,steps_post_sleep_sub,by=c("ID"="ID", "date"="date"))
PA_features_days = left_join(PA_features_days,daily.moving,by=c("ID"="ID", "date"="date"))
PA_features_days = left_join(PA_features_days,daily.sed,by=c("ID"="ID", "date"="date"))
PA_features_days = left_join(PA_features_days,daily.move.over.sed,by=c("ID"="ID", "date"="date"))
PA_features_days = left_join(PA_features_days,active.hours,by=c("ID"="ID", "date"="date"))

PA_features_days <- PA_features_days %>%
  dplyr::rename("daily_steps" = "avg_steps", "daily_activity_index" = "avg_AI")

#join all average physical activity features
PA_features_avg = left_join(daily.steps.avg,daily.AI.avg,by=c("ID"="ID"))
PA_features_avg = left_join(PA_features_avg,avg.pre.sleep.steps,by=c("ID"="ID"))
PA_features_avg = left_join(PA_features_avg,avg.post.wake.steps,by=c("ID"="ID"))
PA_features_avg = left_join(PA_features_avg,daily.move.sed.active.avg,by=c("ID"="ID"))

```