---
title: "Regression analysis between pre-sleep step, energy intake and next-day cgm"
date: "11/12/2022"
author: "Alireza Delfarah"
---

#libraries
```{r}
library(plyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape)
library(reshape2); 
library(grid)
library(gridExtra)
library(scales)
library(RColorBrewer)
library(extrafont)
library(ggpubr)
library(factoextra)
library(matrixStats)
library("writexl")
library(psycho)
library(lubridate)
library("rjson")
library(readtext)
library(readr)
library(stringr)
library(viridis)
library(hms)
library(anytime)
loadfonts()
library(lme4)
library(MuMIn)
```
#import data
```{r}
steps_pre_sleep = read_csv("/Users/delfarah/Desktop/CGM/output/steps_pre_sleep.csv")
```
#plot theme
```{r, plot theme}
theme.heatmap <- theme(panel.border = element_rect(colour = "black", fill=NA, size=0.5), 
                       panel.background = element_rect(fill="white", colour="white", size=0.1,linetype="solid", color="black"),
                       panel.grid.major = element_line(size = 0.1, linetype = 'solid', colour = "grey"),
                       panel.grid.minor = element_line(size = 0.1, linetype = 'solid', colour = "grey"), 
                       axis.ticks.x = element_line(colour="black"),
                       axis.ticks.y = element_line(colour="black"),
                       axis.line = element_line(colour = 'black', size = 0.1), 
                       axis.title=element_text(size=20,face="bold"), 
                       plot.title = element_text(size=18, face="bold"),
                       axis.text.x = element_text(colour = "black", size=20, angle = 90, vjust = 0, face = "bold"), 
                       axis.text.y = element_text(colour = "black",size=20, face = "bold"),
                       legend.title = element_text(size=20,face = "bold"),
                       legend.text = element_text(size=20,face = "bold"))
```
#regression
```{r, regression analysis between pre-sleep steps and next day cgm}

subgroups <- c("IS","IR","Normal","preDM","BC_normal","BC_inter","BC_dys","IE_normal","IE_inter","IE_dys","H_IS","H_inter","H_IR","Adipocyte_IS","Adipocyte_Intermediate","Adipocyte_IR")

plots <- list()
i_sub=0

for (u_sub in unique(subgroups))
{
  i_sub=i_sub+1
  if (i_sub == 1) {data.sub <- steps_pre_sleep %>% subset(sspg_status == u_sub)}
  if (i_sub == 2) {data.sub <- steps_pre_sleep %>% subset(sspg_status == u_sub)}
  if (i_sub == 3) {data.sub <- steps_pre_sleep %>% subset(a1c_t2d_status == u_sub)} 
  if (i_sub == 4) {data.sub <- steps_pre_sleep %>% subset(a1c_t2d_status == u_sub)} 
  if (i_sub == 5) {data.sub <- steps_pre_sleep %>% subset(DI_status == u_sub)} 
  if (i_sub == 6) {data.sub <- steps_pre_sleep %>% subset(DI_status == u_sub)} 
  if (i_sub == 7) {data.sub <- steps_pre_sleep %>% subset(DI_status == u_sub)} 
  if (i_sub == 8) {data.sub <- steps_pre_sleep %>% subset(ie_3_classes == u_sub)} 
  if (i_sub == 9) {data.sub <- steps_pre_sleep %>% subset(ie_3_classes == u_sub)} 
  if (i_sub == 10) {data.sub <- steps_pre_sleep %>% subset(ie_3_classes == u_sub)}
  if (i_sub == 11) {data.sub <- steps_pre_sleep %>% subset(HIR_status == u_sub)}
  if (i_sub == 12) {data.sub <- steps_pre_sleep %>% subset(HIR_status == u_sub)} 
  if (i_sub == 13) {data.sub <- steps_pre_sleep %>% subset(HIR_status == u_sub)} 
  if (i_sub == 14) {data.sub <- steps_pre_sleep %>% subset(FFA_3classes == u_sub)} 
  if (i_sub == 15) {data.sub <- steps_pre_sleep %>% subset(FFA_3classes == u_sub)} 
  if (i_sub == 16) {data.sub <- steps_pre_sleep %>% subset(FFA_3classes == u_sub)} 



  #regression
  
  df_coeff <- data.frame(matrix("", ncol = 4, nrow = 1))  
  x <- c("1h", "2h", "3h", "4h")
  colnames(df_coeff) <- x
  x <- c("beta_coeff")
  rownames(df_coeff) <- x
  
  df_p <- data.frame(matrix("", ncol = 4, nrow = 1))  
  x <- c("1h", "2h", "3h", "4h")
  colnames(df_p) <- x
  x <- c("p_value")
  rownames(df_p) <- x
  
  for (i in 1:4) {
    if (i==1) {reg.mod <- lmer(avg_CGM_next ~ (steps_1h  + `1h_pre_sleep_energy` + (1|ID)), data=data.sub)}
    if (i==2) {reg.mod <- lmer(avg_CGM_next ~ (steps_2h  + `2h_pre_sleep_energy` + (1|ID)), data=data.sub)}
    if (i==3) {reg.mod <- lmer(avg_CGM_next ~ (steps_3h  + `3h_pre_sleep_energy` + (1|ID)), data=data.sub)}
    if (i==4) {reg.mod <- lmer(avg_CGM_next ~ (steps_4h  + `4h_pre_sleep_energy` + (1|ID)), data=data.sub)}
    anova(reg.mod); summary(reg.mod)
    r.squaredGLMM(reg.mod)  #R2 for mixed effect models 
    
    # extract coefficients
    coefs <- data.frame(coef(summary(reg.mod)))
    # use normal distribution to approximate p-value
    coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
      
    df_coeff[1,i] <- coefs[2,1]
    df_p[1,i] <- coefs[2,4]
    }
  
  if (i_sub == 1) {
    df_coeff.all <- df_coeff[1,]
    df_coeff.all <- df_coeff.all[-1,]
    df_p.all <- df_p[1,]
    df_p.all <- df_p.all[-1,]
    }
  df_coeff.all <- rbind(df_coeff.all,df_coeff)
  df_p.all <- rbind(df_p.all,df_p)
}

df_coeff.all <- as.data.frame(sapply(df_coeff.all, as.numeric))
df_p.all <- as.data.frame(sapply(df_p.all, as.numeric))


x <- c("IS","IR","Normal","preDM","BC_normal","BC_inter","BC_dys","IE_normal","IE_inter","IE_dys","H_IS","H_inter","H_IR","Adipocyte_IS","Adipocyte_Intermediate","Adipocyte_IR")
x <- c("IS","IR","Normal","preDM","BC_normal","BC_inter","BC_dys","IE_normal","IE_inter","IE_dys")

rownames(df_coeff.all) <- x
rownames(df_p.all) <- x

#corr coeffs
temp1 <- df_coeff.all
temp1$var <- rownames(temp1)
melt.temp1 = melt(temp1, id = "var")
x <- c("subgroup", "steps", "beta_coeff")
colnames(melt.temp1) <- x
melt.temp1$subgroup <- factor(melt.temp1$subgroup, levels=c("IS","IR","Normal","preDM","BC_normal","BC_inter","BC_dys","IE_normal","IE_inter","IE_dys","H_IS","H_inter","H_IR","Adipocyte_IS","Adipocyte_Intermediate","Adipocyte_IR"))

#p-values
temp2 <- df_p.all
temp2$var <- rownames(temp2)
melt.temp2 = melt(temp2, id = "var")
x <- c("subgroup", "steps", "p.value")
colnames(melt.temp2) <- x
melt.temp2$subgroup <- factor(melt.temp2$subgroup, levels=c("IS","IR","Normal","preDM","BC_normal","BC_inter","BC_dys","IE_normal","IE_inter","IE_dys","H_IS","H_inter","H_IR","Adipocyte_IS","Adipocyte_Intermediate","Adipocyte_IR"))

melt.combined = left_join(melt.temp1,melt.temp2,by=c("subgroup"="subgroup", "steps"="steps"))
melt.combined$p.value[melt.combined$p.value > 0.05] <- NA
melt.combined$p.value[melt.combined$p.value < 0.05] <- "*"
melt.combined$p.value[is.na(melt.combined$beta_coeff)] <- NA
melt.combined$p.value[!is.na(melt.combined$p.value)] <- formatC(melt.combined$p.value[!is.na(melt.combined$p.value)], format = "e", digits = 0)
melt.combined$subgroup <- as.character(melt.combined$subgroup)
melt.combined[melt.combined == "IS"] <- "Insulin Sensitive"
melt.combined[melt.combined == "IR"] <- "Insulin Resistant"
melt.combined[melt.combined == "preDM"] <- "PreDM"
melt.combined[melt.combined == "BC_normal"] <- "BC_Normal"
melt.combined[melt.combined == "BC_inter"] <- "BC_Intermediate"
melt.combined[melt.combined == "BC_dys"] <- "BC_Dysfunction"
melt.combined[melt.combined == "IE_inter"] <- "IE_Intermediate"
melt.combined[melt.combined == "IE_dys"] <- "IE_Dysfunction"
melt.combined[melt.combined == "IE_normal"] <- "IE_Normal"
melt.combined[melt.combined == "H_inter"] <- "H_Intermediate"
melt.combined$subgroup <- factor(melt.combined$subgroup, levels=c("Insulin Sensitive","Insulin Resistant","Normal","PreDM","BC_Normal","BC_Intermediate","BC_Dysfunction","IE_Normal","IE_Intermediate","IE_Dysfunction","H_IS","H_Intermediate","H_IR","Adipocyte_IS","Adipocyte_Intermediate","Adipocyte_IR"))
melt.combined <- melt.combined %>%
  dplyr::rename("Beta_coefficient" = "beta_coeff")


#plot heatmap
dodge <- position_dodge(width=0.9)

plots[[1]] <- ggplot(melt.combined, aes(steps, subgroup, fill= Beta_coefficient)) + 
  geom_tile() +
  coord_equal() +
  geom_text(aes(label=p.value), size = 12, fontface = "bold") +
  scale_fill_gradient2(low="blue", mid="white", high="red", 
                       midpoint=0,    
                       #breaks=seq(0), 
                       limits=c(-3.5e-2, 3.5e-2)) +
  xlab("Steps before bed-time") +
  ylab("Next-day CGM (mean)") +
  ggtitle("") +
  theme.heatmap 

#healthy subgroups
temp.plot <- melt.combined %>% subset(subgroup == "Insulin Sensitive" | subgroup == "Normal" | subgroup == "BC_Normal" | subgroup == "IE_Normal" | subgroup == "H_IS" | subgroup == "Adipocyte_IS")

#plot heatmap
dodge <- position_dodge(width=0.9)

plots[[2]] <- ggplot(temp.plot, aes(steps, subgroup, fill= Beta_coefficient)) + 
  geom_tile() +
  coord_equal() +
  geom_text(aes(label=p.value), size = 12, fontface = "bold") +
  scale_fill_gradient2(low="blue", mid="white", high="red", 
                       midpoint=0,    
                       #breaks=seq(0), 
                       limits=c(-3.5e-2, 3.5e-2)) +
  xlab("Steps before bed-time") +
  ylab("Next-day CGM (mean)") +
  ggtitle("") +
  theme.heatmap 


#unhealthy subgroups
temp.plot <- melt.combined %>% subset(subgroup == "Insulin esistant" | subgroup == "PreDM" | subgroup == "BC_Dysfunction" | subgroup == "IE_Dysfunction" | subgroup == "H_IR" | subgroup == "Adipocyte_IR")

#plot heatmap
dodge <- position_dodge(width=0.9)

plots[[3]] <- ggplot(temp.plot, aes(steps, subgroup, fill= Beta_coefficient)) + 
  geom_tile() +
  coord_equal() +
  geom_text(aes(label=p.value), size = 12, fontface = "bold") +
  scale_fill_gradient2(low="blue", mid="white", high="red", 
                       midpoint=0,    
                       #breaks=seq(0), 
                       limits=c(-3.5e-2, 3.5e-2)) +
  xlab("Steps before bed-time") +
  ylab("Next-day CGM (mean)") +
  ggtitle("") +
  theme.heatmap 

#intermediate subgroups
temp.plot <- melt.combined %>% subset(subgroup == "BC_Intermediate" | subgroup == "IE_Intermediate" | subgroup == "H_inter" | subgroup == "Adipocyte_Intermediate")

#plot heatmap
dodge <- position_dodge(width=0.9)

plots[[4]] <- ggplot(temp.plot, aes(steps, subgroup, fill= Beta_coefficient)) + 
  geom_tile() +
  coord_equal() +
  geom_text(aes(label=p.value), size = 12, fontface = "bold") +
  scale_fill_gradient2(low="blue", mid="white", high="red", 
                       midpoint=0,    
                       #breaks=seq(0), 
                       limits=c(-3.5e-2, 3.5e-2)) +
  xlab("Steps before bed-time") +
  ylab("Next-day CGM (mean)") +
  ggtitle("") +
  theme.heatmap 

plots <- marrangeGrob(plots, nrow=1, ncol=1)
setwd("~/Desktop/git/CGM/")
ggsave(file=paste("lmer_steps_pre_sleep_next_day_CGM_energy_continous.pdf", sep = ""), plots, width=11,height=8)

```