---
title: "Shifted correlation analysis between step count and CGM for metabolic subphenotypes"
date: "11/12/2022"
author: "Alireza Delfarah"
---

#load data
```{r, }
daily_zones_data = read_csv("~/Desktop/git/CGM/daily_zones_cgm_physical_activity_diet.csv")
daily_zones_data <- daily_zones_data %>% select(-X1)
```
#shifted correlation
```{r, shifted correlation analysis with samling and permutation}

#################################################################################################
#correlation of steps with cgm in different time zones with sampling and permutation
#################################################################################################
#for each metabolic subphenotype
#sample 10 consecutive days for each participant
#combine data for all participants of that metabolic subphenotype
#perform a shifted pearson correlation analysis between cgm and steps
#repeat 10 permutations of the shifted correlation analysis
#calculate average correlation coefficients from 10 permutations
#calculate p-value of the 10 permutations (test if correlation coefficients from permutations are significantly different from 0 as if there was no correlation)
####################################################################################


###################################################
###################################################
#steps v. cgm next 0-24 h
###################################################
###################################################

subgroups <- c("IS","IR","Normal","preDM","BC_normal","BC_inter","BC_dys","IE_normal","IE_inter","IE_dys","H_IS","H_inter","H_IR","Adipocyte_IS","Adipocyte_Intermediate","Adipocyte_IR")

sample_size = 10
perm_num = 10
perm_num_minus = perm_num - 1
i_sub=0
plots<- list()

for (u_sub in unique(subgroups))
{
i_sub=i_sub+1
if (i_sub == 1) {data.sub <- daily_zones_data %>% subset(sspg_status == u_sub)}
if (i_sub == 2) {data.sub <- daily_zones_data %>% subset(sspg_status == u_sub)}
if (i_sub == 3) {data.sub <- daily_zones_data %>% subset(a1c_t2d_status == u_sub)} 
if (i_sub == 4) {data.sub <- daily_zones_data %>% subset(a1c_t2d_status == u_sub)} 
if (i_sub == 5) {data.sub <- daily_zones_data %>% subset(DI_status == u_sub)} 
if (i_sub == 6) {data.sub <- daily_zones_data %>% subset(DI_status == u_sub)} 
if (i_sub == 7) {data.sub <- daily_zones_data %>% subset(DI_status == u_sub)} 
if (i_sub == 8) {data.sub <- daily_zones_data %>% subset(ie_3_classes == u_sub)} 
if (i_sub == 9) {data.sub <- daily_zones_data %>% subset(ie_3_classes == u_sub)} 
if (i_sub == 10) {data.sub <- daily_zones_data %>% subset(ie_3_classes == u_sub)}
if (i_sub == 11) {data.sub <- daily_zones_data %>% subset(HIR_status == u_sub)}
if (i_sub == 12) {data.sub <- daily_zones_data %>% subset(HIR_status == u_sub)} 
if (i_sub == 13) {data.sub <- daily_zones_data %>% subset(HIR_status == u_sub)} 
if (i_sub == 14) {data.sub <- daily_zones_data %>% subset(FFA_3classes == u_sub)} 
if (i_sub == 15) {data.sub <- daily_zones_data %>% subset(FFA_3classes == u_sub)} 
if (i_sub == 16) {data.sub <- daily_zones_data %>% subset(FFA_3classes == u_sub)} 


if (nrow(data.sub) <= sample_size){next}

test <- list()

df <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.zone.corr1", "steps.zone.corr2", "steps.zone.corr3", "steps.zone.corr4", "steps.zone.corr5", "steps.zone.corr6", "steps.zone.corr7")
colnames(df) <- x

df <- as.data.frame(sapply(df, as.numeric))

x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(df) <- x

for (t in 1:perm_num)
{

sampling <- data.sub[1,]
sampling <- sampling[-1,]
  
for (u in (unique(data.sub$ID)))
  
{
  data.temp <- data.sub %>% subset(ID == u)
  if (nrow(data.temp) < sample_size){next}
  sampling_index = nrow(data.temp) - sample_size + 1
  start_index <- sample(1:sampling_index, 1)
  end_index <- start_index + sample_size - 1
  sampling <- rbind(sampling,data.temp[start_index:end_index, ])
}

test[[t]] <- df

for (i in 1:7)
{
  #i for CGM
  for (j in 1:7)
  {
  #j for steps
    temp <- sampling
    #skip if more than half of the cgm or carb values are zero for that time-window
    if (sum(temp[,i+5] == 0) > nrow(temp)/4*3){next}
    if (sum(temp[,j+12] == 0) > nrow(temp)/4*3){next}
    cgm.temp <- temp[,i+5]
    cgm.temp <- cgm.temp[!is.na(cgm.temp)]
    steps.temp <- temp[,j+12]
    steps.temp <- steps.temp[!is.na(steps.temp)]
    res <- cor.test(cgm.temp, steps.temp, method = "pearson")
    test[[t]][i,j] <- res$estimate
  }}
}

#combine correlation matrices from permutations
test.combined <- test[[1]][1,]
test.combined <- test.combined[-1,]

for (i in 1:perm_num)
{
  test.combined <- rbind(test.combined,test[[i]])
}


#avg correlation matrices from permutations
test.avg <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.zone.corr1", "steps.zone.corr2", "steps.zone.corr3", "steps.zone.corr4", "steps.zone.corr5", "steps.zone.corr6", "steps.zone.corr7")
colnames(test.avg) <- x
test.avg <- as.data.frame(sapply(test.avg, as.numeric))
x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(test.avg) <- x


test.p <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.pvalue.corr1", "steps.pvalue.corr2", "steps.pvalue.corr3", "steps.pvalue.corr4", "steps.pvalue.corr5", "steps.pvalue.corr6", "steps.pvalue.corr7")
colnames(test.p) <- x
test.p <- as.data.frame(sapply(test.p, as.numeric))
x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(test.p) <- x

for (i in 1:7)
{
  for (j in 1:7)
  {
    ii <- (7*c(0:perm_num_minus))+i
    test.avg[i,j] <- mean(test.combined[ii,j])
    tt <- t.test(test.combined[ii,j], mu = 0)
    test.p[i,j] <- tt$p.value
  }
}
    
#corr coeffs
temp1 <- test.avg
tri.temp <- upper.tri(temp1, diag = FALSE)
temp1[tri.temp] <- NA
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
colnames(temp1) <- x
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
rownames(temp1) <- x
temp1$var <- rownames(temp1)
melt.temp1 = melt(temp1, id = "var")
x <- c("CGM", "steps", "corr_coeff")
colnames(melt.temp1) <- x
melt.temp1$CGM <- factor(melt.temp1$CGM, levels=c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am"))


#p-values
temp2 <- test.p
tri.temp <- upper.tri(temp2, diag = FALSE)
temp2[tri.temp] <- NA
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
colnames(temp2) <- x
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
rownames(temp2) <- x
temp2$var <- rownames(temp2)
melt.temp2 = melt(temp2, id = "var")
x <- c("CGM", "steps", "perm.p.value")
colnames(melt.temp2) <- x
melt.temp2$CGM <- factor(melt.temp2$CGM, levels=c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am"))

melt.cgm.steps.perm = left_join(melt.temp1,melt.temp2,by=c("CGM"="CGM", "steps"="steps"))
melt.cgm.steps.perm$corr_coeff <- round(melt.cgm.steps.perm$corr_coeff,digits=2)
melt.cgm.steps.perm$perm.p.value[melt.cgm.steps.perm$perm.p.value > 0.001] <- NA
melt.cgm.steps.perm$perm.p.value[melt.cgm.steps.perm$perm.p.value < 0.001] <- "*"
melt.cgm.steps.perm$perm.p.value[!is.na(melt.cgm.steps.perm$perm.p.value)] <- formatC(melt.cgm.steps.perm$perm.p.value[!is.na(melt.cgm.steps.perm$perm.p.value)], format = "e", digits = 0)

###################################################
###################################################
#steps v. cgm next 24-48h
###################################################
###################################################

test <- list() 

df <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.zone.corr1", "steps.zone.corr2", "steps.zone.corr3", "steps.zone.corr4", "steps.zone.corr5", "steps.zone.corr6", "steps.zone.corr7")
colnames(df) <- x

df <- as.data.frame(sapply(df, as.numeric))

x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(df) <- x


for (t in 1:perm_num)
{
  sampling <- data.sub[1,]
  sampling <- sampling[-1,]
  for (u in (unique(data.sub$ID)))
    
  {
    data.temp <- data.sub %>% subset(ID == u)
    if (nrow(data.temp) < sample_size){next}
    sampling_index = nrow(data.temp) - sample_size + 1
    start_index <- sample(1:sampling_index, 1)
    end_index <- start_index + sample_size - 1
    sampling <- rbind(sampling,data.temp[start_index:end_index, ])
  }
  
test[[t]] <- df
a <- nrow(sampling)/sample_size
ii <- sample_size*c(0:(a-1)) + 1
jj <- sample_size*c(1:a)
  
  for (i in 1:7)
  {
    #i for CGM
    for (j in 1:7)
    {
      #j for steps
      temp <- sampling
      #skip if more than half of the cgm or carb values are zero for that time-window
      if (sum(temp[,i+5] == 0) > nrow(temp)/4*3){next}
      if (sum(temp[,j+12] == 0) > nrow(temp)/4*3){next}
      temp[ii,i+5] <- NA
      temp[jj,j+12] <- NA
      cgm.temp <- temp[,i+5]
      cgm.temp <- cgm.temp[!is.na(cgm.temp)]
      steps.temp <- temp[,j+12]
      steps.temp <- steps.temp[!is.na(steps.temp)]
      res <- cor.test(cgm.temp, steps.temp, method = "pearson")
      test[[t]][i,j] <- res$estimate
      #test[i,j+7] <- res$p.value
    }}
}

#combine correlation matrices from permutations
test.combined <- test[[1]][1,]
test.combined <- test.combined[-1,]

for (i in 1:perm_num)
{
  test.combined <- rbind(test.combined,test[[i]])
}

#avg correlation matrices from permutations
test.avg <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.zone.corr1", "steps.zone.corr2", "steps.zone.corr3", "steps.zone.corr4", "steps.zone.corr5", "steps.zone.corr6", "steps.zone.corr7")
colnames(test.avg) <- x
test.avg <- as.data.frame(sapply(test.avg, as.numeric))
x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(test.avg) <- x

test.p <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.pvalue.corr1", "steps.pvalue.corr2", "steps.pvalue.corr3", "steps.pvalue.corr4", "steps.pvalue.corr5", "steps.pvalue.corr6", "steps.pvalue.corr7")
colnames(test.p) <- x
test.p <- as.data.frame(sapply(test.p, as.numeric))
x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(test.p) <- x

for (i in 1:7)
{
  for (j in 1:7)
  {
    ii <- (7*c(0:perm_num_minus))+i
    test.avg[i,j] <- mean(test.combined[ii,j])
    tt <- t.test(test.combined[ii,j], mu = 0)
    test.p[i,j] <- tt$p.value
  }
}

#corr coeffs
temp1 <- test.avg

x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
colnames(temp1) <- x
x <- c("12am-5am+24h","5am-8am+24h","8am-11am+24h","11am-2pm+24h", "2pm-5pm+24h", "5pm-9pm+24h", "9pm-12am+24h")
rownames(temp1) <- x
temp1$var <- rownames(temp1)
melt.temp1 = melt(temp1, id = "var")
x <- c("CGM", "steps", "corr_coeff")
colnames(melt.temp1) <- x
melt.temp1$CGM <- factor(melt.temp1$CGM, levels=c("12am-5am+24h","5am-8am+24h","8am-11am+24h","11am-2pm+24h", "2pm-5pm+24h", "5pm-9pm+24h", "9pm-12am+24h"))

#p-values
temp2 <- test.p
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
colnames(temp2) <- x
x <- c("12am-5am+24h","5am-8am+24h","8am-11am+24h","11am-2pm+24h", "2pm-5pm+24h", "5pm-9pm+24h", "9pm-12am+24h")
rownames(temp2) <- x
temp2$var <- rownames(temp2)
melt.temp2 = melt(temp2, id = "var")
x <- c("CGM", "steps", "perm.p.value")
colnames(melt.temp2) <- x
melt.temp2$CGM <- factor(melt.temp2$CGM, levels=c("12am-5am+24h","5am-8am+24h","8am-11am+24h","11am-2pm+24h", "2pm-5pm+24h", "5pm-9pm+24h", "9pm-12am+24h"))

melt.cgm.steps.perm.next = left_join(melt.temp1,melt.temp2,by=c("CGM"="CGM", "steps"="steps"))
melt.cgm.steps.perm.next$corr_coeff <- round(melt.cgm.steps.perm.next$corr_coeff,digits=2)
melt.cgm.steps.perm.next$perm.p.value[melt.cgm.steps.perm.next$perm.p.value > 0.001] <- NA
melt.cgm.steps.perm.next$perm.p.value[melt.cgm.steps.perm.next$perm.p.value < 0.001] <- "*"
melt.cgm.steps.perm.next$perm.p.value[!is.na(melt.cgm.steps.perm.next$perm.p.value)] <- formatC(melt.cgm.steps.perm.next$perm.p.value[!is.na(melt.cgm.steps.perm.next$perm.p.value)], format = "e", digits = 0)

###################################################
###################################################
#steps v. cgm next 48-72h
###################################################
###################################################

test <- list() 

df <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.zone.corr1", "steps.zone.corr2", "steps.zone.corr3", "steps.zone.corr4", "steps.zone.corr5", "steps.zone.corr6", "steps.zone.corr7")
colnames(df) <- x

df <- as.data.frame(sapply(df, as.numeric))

x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(df) <- x

for (t in 1:perm_num)
{
  sampling <- data.sub[1,]
  sampling <- sampling[-1,]
  for (u in (unique(data.sub$ID)))
    
  {
    data.temp <- data.sub %>% subset(ID == u)
    if (nrow(data.temp) <= sample_size){next}
    sampling_index = nrow(data.temp) - sample_size + 1
    start_index <- sample(1:sampling_index, 1)
    end_index <- start_index + sample_size - 1
    sampling <- rbind(sampling,data.temp[start_index:end_index, ])
  }
  
test[[t]] <- df
a <- nrow(sampling)/sample_size
ii <- sample_size*c(0:(a-1)) + 1
ii2 <- sample_size*c(0:(a-1)) + 2
ii3 <- as.numeric(rbind(ii2,ii))
jj <- sample_size*c(1:a)
jj2 <- sample_size*c(1:a) - 1 
jj3 <- as.numeric(rbind(jj2,jj))
  for (i in 1:7)
  {
    #i for CGM
    for (j in 1:7)
    {
      #j for steps
      temp <- sampling
      #skip if more than half of the cgm or carb values are zero for that time-window
      if (sum(temp[,i+5] == 0) > nrow(temp)/4*3){next}
      if (sum(temp[,j+12] == 0) > nrow(temp)/4*3){next}
      temp[ii3,i+5] <- NA
      temp[jj3,j+12] <- NA
      cgm.temp <- temp[,i+5]
      cgm.temp <- cgm.temp[!is.na(cgm.temp)]
      steps.temp <- temp[,j+12]
      steps.temp <- steps.temp[!is.na(steps.temp)]
      res <- cor.test(cgm.temp, steps.temp, method = "pearson")
      test[[t]][i,j] <- res$estimate
      #test[i,j+7] <- res$p.value
    }}
}

#combine correlation matrices from permutations
test.combined <- test[[1]][1,]
test.combined <- test.combined[-1,]

for (i in 1:perm_num)
{
  test.combined <- rbind(test.combined,test[[i]])
}

#avg correlation matrices from permutations
test.avg <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.zone.corr1", "steps.zone.corr2", "steps.zone.corr3", "steps.zone.corr4", "steps.zone.corr5", "steps.zone.corr6", "steps.zone.corr7")
colnames(test.avg) <- x
test.avg <- as.data.frame(sapply(test.avg, as.numeric))
x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(test.avg) <- x

test.p <- data.frame(matrix("", ncol = 7, nrow = 7))  
x <- c("steps.pvalue.corr1", "steps.pvalue.corr2", "steps.pvalue.corr3", "steps.pvalue.corr4", "steps.pvalue.corr5", "steps.pvalue.corr6", "steps.pvalue.corr7")
colnames(test.p) <- x
test.p <- as.data.frame(sapply(test.p, as.numeric))
x <- c("CGM.zone1", "CGM.zone2", "CGM.zone3", "CGM.zone4", "CGM.zone5", "CGM.zone6", "CGM.zone7")
rownames(test.p) <- x

for (i in 1:7)
{
  for (j in 1:7)
  {
    ii <- (7*c(0:perm_num_minus))+i
    test.avg[i,j] <- mean(test.combined[ii,j])
    tt <- t.test(test.combined[ii,j], mu = 0)
    test.p[i,j] <- tt$p.value
  }
}

#corr coeffs
temp1 <- test.avg
tri.temp <- lower.tri(temp1, diag = FALSE)
temp1[tri.temp] <- NA
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
colnames(temp1) <- x
x <- c("12am-5am+48h","5am-8am+48h","8am-11am+48h","11am-2pm+48h", "2pm-5pm+48h", "5pm-9pm+48h", "9pm-12am+48h")
rownames(temp1) <- x
temp1$var <- rownames(temp1)
melt.temp1 = melt(temp1, id = "var")
x <- c("CGM", "steps", "corr_coeff")
colnames(melt.temp1) <- x
melt.temp1$CGM <- factor(melt.temp1$CGM, levels=c("12am-5am+48h","5am-8am+48h","8am-11am+48h","11am-2pm+48h", "2pm-5pm+48h", "5pm-9pm+48h", "9pm-12am+48h"))

#p-values
temp2 <- test.p
tri.temp <- lower.tri(temp2, diag = FALSE)
temp2[tri.temp] <- NA
x <- c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am")
colnames(temp2) <- x
x <- c("12am-5am+48h","5am-8am+48h","8am-11am+48h","11am-2pm+48h", "2pm-5pm+48h", "5pm-9pm+48h", "9pm-12am+48h")
rownames(temp2) <- x
temp2$var <- rownames(temp2)
melt.temp2 = melt(temp2, id = "var")
x <- c("CGM", "steps", "perm.p.value")
colnames(melt.temp2) <- x
melt.temp2$CGM <- factor(melt.temp2$CGM, levels=c("12am-5am+48h","5am-8am+48h","8am-11am+48h","11am-2pm+48h", "2pm-5pm+48h", "5pm-9pm+48h", "9pm-12am+48h"))

melt.cgm.steps.perm.next2 = left_join(melt.temp1,melt.temp2,by=c("CGM"="CGM", "steps"="steps"))
melt.cgm.steps.perm.next2$corr_coeff <- round(melt.cgm.steps.perm.next2$corr_coeff,digits=2)
melt.cgm.steps.perm.next2$perm.p.value[melt.cgm.steps.perm.next2$perm.p.value > 0.001] <- NA
melt.cgm.steps.perm.next2$perm.p.value[melt.cgm.steps.perm.next2$perm.p.value < 0.001] <- "*"
melt.cgm.steps.perm.next2$perm.p.value[!is.na(melt.cgm.steps.perm.next2$perm.p.value)] <- formatC(melt.cgm.steps.perm.next2$perm.p.value[!is.na(melt.cgm.steps.perm.next2$perm.p.value)], format = "e", digits = 0)
melt.cgm.steps.perm.next2.comb <- melt.cgm.steps.perm.next2
melt.cgm.steps.perm.next2.comb$perm.p.value[is.na(melt.cgm.steps.perm.next2.comb$corr_coeff)] <- NA
melt.cgm.steps.perm.next2.comb <- rbind(melt.cgm.steps.perm,melt.cgm.steps.perm.next,melt.cgm.steps.perm.next2)
melt.cgm.steps.perm.next2.comb$CGM <- factor(melt.cgm.steps.perm.next2.comb$CGM, levels=c("12am-5am","5am-8am","8am-11am","11am-2pm", "2pm-5pm", "5pm-9pm", "9pm-12am", "12am-5am+24h","5am-8am+24h","8am-11am+24h","11am-2pm+24h", "2pm-5pm+24h", "5pm-9pm+24h", "9pm-12am+24h", "12am-5am+48h","5am-8am+48h","8am-11am+48h","11am-2pm+48h", "2pm-5pm+48h", "5pm-9pm+48h", "9pm-12am+48h"))
melt.cgm.steps.perm.next2.comb <- melt.cgm.steps.perm.next2.comb %>%
  rename("Steps" = "steps", "correlation_coefficient" = "corr_coeff")

if (u_sub == "H_IS") {temp_H_IS <- melt.cgm.steps.perm.next2.comb}

num_cases = nrow(sampling) / sample_size

if (u_sub == "IS") {u_sub = "Insulin Sensitive"}
if (u_sub == "IR") {u_sub = "Insulin Resistant"}
if (u_sub == "preDM") {u_sub = "PreDM"}
if (u_sub == "BC_normal") {u_sub = "BC_Normal"}
if (u_sub == "BC_inter") {u_sub = "BC_Intermediate"}
if (u_sub == "BC_dys") {u_sub = "BC_Dysfunction"}
if (u_sub == "IE_inter") {u_sub = "IE_Intermediate"}
if (u_sub == "IE_dys") {u_sub = "IE_Dysfunction"}
if (u_sub == "IE_Normal") {u_sub = "IE_Normal"}
if (u_sub == "H_inter") {u_sub = "H_Intermediate"}

p_title <- paste(u_sub)

#plot heatmap
dodge <- position_dodge(width=0.9)

plots[[i_sub]] <- ggplot(melt.cgm.steps.perm.next2.comb, aes(CGM, Steps, fill= correlation_coefficient)) + 
  geom_tile() +
  coord_equal() +
  geom_text(aes(label=perm.p.value), size = 6, fontface = "bold") +
  scale_fill_gradient2(low="blue", mid="white", high="red", 
                       midpoint=0,    
                       limits=c(-0.5, 0.5)) +
  xlab("CGM (mean)") +
  ylab("Step Count") +
  ggtitle(p_title) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=0.5), 
                       panel.background = element_rect(fill="white", colour="white", size=0.1,linetype="solid", color="black"),
                       panel.grid.major = element_line(size = 0.1, linetype = 'solid', colour = "grey"),
                       panel.grid.minor = element_line(size = 0.1, linetype = 'solid', colour = "grey"), 
                       axis.ticks.x = element_line(colour="black"),
                       axis.ticks.y = element_line(colour="black"),
                       axis.line = element_line(colour = 'black', size = 0.1), 
                       axis.title=element_text(size=20,face="bold"), 
                       plot.title = element_text(size=21, face="bold"),
                       axis.text.x = element_text(colour = "black", size=16, angle = 90, vjust = 0.5, hjust = 1, face = "bold"), 
                       axis.text.y = element_text(colour = "black",size=16, face = "bold"),
                       legend.title = element_text(size=14,face = "bold"),
                       legend.text = element_text(size=14,face = "bold")) 
}

```
#export plots
```{r, plotting}
plots_arrange <- marrangeGrob(plots, nrow=1, ncol=1)
setwd("~/Desktop/git/CGM")
ggsave(file="CGM_steps_shifted_correlation.pdf", plots_arrange, width=11,height=8)

```
